import type { EncyclopediaEntry } from '../../core/defs';

/** Ansiklopedi — KİŞİLER (Osmanlı ve Bizans/Latin tarafı). */
export const ENC_KISILER: EncyclopediaEntry[] = [
  // ───────────── Osmanlı ─────────────
  {
    id: 'fatih',
    title: 'II. Mehmed (Fatih Sultan Mehmed)',
    category: 'kisi',
    subtitle: 'Osmanlı sultanı (1444–1446, 1451–1481)',
    body: [
      '1432’de Edirne’de doğdu. Babası II. Murad’ın sağlığında kısa bir süre tahta çıktı; 1451 başında babasının ölümüyle ikinci kez padişah oldu. Kostantiniyye’yi aldığında yirmi bir yaşındaydı.',
      'Tahta çıkar çıkmaz batıdaki cepheleri antlaşmalarla yatıştırdı, 1452’de Boğazkesen’i (Rumeli Hisarı) yaptırdı, büyük toplar döktürdü ve kuşatmayı bizzat yönetti. Otağını Topkapı karşısına kurdu; gemilerin karadan Haliç’e indirilmesi gibi kararlar Osmanlı kaynaklarında onun tedbiri olarak anlatılır.',
      'Fetihten sonra şehri imar edip yeniden iskân ettirdi, Rum Ortodoks patrikliğini yeniden kurdurdu ve Galata’ya ahidname verdi. Osmanlı geleneği ona “Ebü’l-Feth”, yani fetihlerin babası der; Tursun Bey’in eseri adını buradan alır.',
    ],
    sources: ['tursun', 'apz', 'kritovulos', 'inalcik', 'emecen'],
    related: ['halil-pasa', 'zaganos-pasa', 'aksemseddin', 'otag', 'kaynak-tursun'],
  },
  {
    id: 'halil-pasa',
    title: 'Çandarlı Halil Paşa',
    category: 'kisi',
    subtitle: 'Sadrazam, barış kanadının önderi',
    body: [
      'Osmanlı devletine nesiller boyu vezir yetiştiren Çandarlı ailesindendir. II. Murad döneminde sadrazamdı ve II. Mehmed’in ilk saltanatında da devlet işlerini fiilen o yürütmüştü.',
      'Kuşatmaya baştan beri temkinle yaklaştı: Haçlı birliğinin yeniden kurulmasından, Macar ve Venedik müdahalesinden ve kuşatmanın masrafından çekiniyordu. Bizans’la ilişkileri yüzünden çevresinde “gâvur dostu” diye konuşulduğu da anlatılır; bu iddiaların ne kadarının gerçek olduğu tartışmalıdır.',
      'Rumeli Hisarı’nın kulelerinden birini o yaptırdı ve kuşatma boyunca sadrazamlıkta kaldı. Fetihten kısa süre sonra azledildi ve idam edildi. Oyunda Divan’ın barış kanadını temsil eder.',
    ],
    sources: ['inalcik', 'emecen', 'apz', 'doukas'],
    related: ['zaganos-pasa', 'divan', 'rumeli-hisari'],
  },
  {
    id: 'zaganos-pasa',
    title: 'Zağanos Paşa',
    category: 'kisi',
    subtitle: 'İkinci vezir, savaş kanadının önderi',
    body: [
      'Devşirme kökenli bir vezir ve genç Sultan’ın en yakın adamlarından biriydi. Halil Paşa’nın karşısında kuşatmanın sürdürülmesini savunan savaş kanadının başını çekti.',
      'Kuşatmada Haliç’in kuzeyinde, Galata’nın arkasındaki sırtlarda konuşlandı; gemilerin karadan indirilmesi, Haliç üzerindeki fıçı köprü ve lağımlar onun kesiminde yürütüldü. Rumeli Hisarı’nın kulelerinden birini de o yaptırdı.',
      'Fetihten sonra Halil Paşa’nın yerine sadrazam oldu (doğrulanacak: görev süresi). Oyunda lağım, köprü ve gemi işlerinde bonus verir ve Divan’ı savaştan yana çeker.',
    ],
    sources: ['emecen', 'inalcik', 'kritovulos'],
    related: ['halil-pasa', 'divan', 'gemilerin-karadan-yurutulmesi', 'lagim'],
    dogrulanacak: true,
  },
  {
    id: 'saruca-pasa',
    title: 'Saruca Paşa',
    category: 'kisi',
    subtitle: 'Vezir, Rumeli Hisarı’nın kule yapıcılarından',
    body: [
      'Rumeli Hisarı’nın üç büyük kulesinden birini yaptıran vezirdir; kulelerden biri bugün de onun adıyla anılır.',
      'Kuşatmada merkezde görev aldığı kabul edilir. Hayatına dair ayrıntılar kaynaklarda sınırlıdır (doğrulanacak).',
    ],
    sources: ['apz', 'emecen'],
    related: ['rumeli-hisari', 'halil-pasa', 'zaganos-pasa'],
    dogrulanacak: true,
  },
  {
    id: 'karaca-pasa',
    title: 'Dayı Karaca Paşa',
    category: 'kisi',
    subtitle: 'Rumeli beylerbeyi',
    body: [
      'Kuşatma sırasında Rumeli beylerbeyiydi. Rumeli’nin tımarlı sipahileriyle ordunun sol kanadını, Haliç’ten Blahernai surlarına kadar uzanan kesimi tuttu.',
      'Kuşatmadan önce, 1452–53 kışında Trakya’daki Bizans’a bağlı kasabalara gönderildiği anlatılır. 1456 Belgrad kuşatmasında öldü.',
    ],
    sources: ['kritovulos', 'emecen', 'tansel'],
    related: ['ishak-pasa', 'blahernai', 'timar'],
  },
  {
    id: 'ishak-pasa',
    title: 'İshak Paşa',
    category: 'kisi',
    subtitle: 'Anadolu beylerbeyi',
    body: [
      'Kuşatmada Anadolu beylerbeyiydi ve Anadolu askerleriyle sağ kanadı, Topkapı’dan Marmara kıyısına kadar uzanan kesimi tuttu.',
      'Son hücumda ikinci dalgayı oluşturan Anadolu askerleri onun komutasındaydı. Sonraki yıllarda sadrazamlığa kadar yükseldi.',
    ],
    sources: ['kritovulos', 'emecen', 'tansel'],
    related: ['karaca-pasa', 'son-hucum'],
  },
  {
    id: 'baltaoglu',
    title: 'Baltaoğlu Süleyman Bey',
    category: 'kisi',
    subtitle: 'Donanma komutanı',
    body: [
      'Kuşatmanın başında Osmanlı donanmasının komutanıydı. Donanma Beşiktaş’ta, Çifte Sütunlar (Diplokionion) önünde demirlemişti.',
      'Kuşatmanın ilk günlerinde Büyükada’daki Bizans kulesini aldı. 20 Nisan’da üç Ceneviz gemisi ile bir Bizans gemisinin ablukayı yarmasını önleyemeyince görevden alındı; yerine Hamza Bey getirildi. Cezalandırılışının ayrıntıları kaynaklarda farklıdır (doğrulanacak).',
    ],
    sources: ['kritovulos', 'emecen', 'barbaro'],
    related: ['hamza-bey', 'deniz-savasi', 'kadirga'],
  },
  {
    id: 'hamza-bey',
    title: 'Hamza Bey',
    category: 'kisi',
    subtitle: 'Baltaoğlu’nun ardından donanma komutanı',
    body: [
      '20 Nisan yenilgisinden sonra donanmanın başına getirildi. Kuşatmanın geri kalanında Haliç’e indirilen gemiler ve Marmara’daki filo onun sorumluluğundaydı.',
      'Kaynaklarda aynı adı taşıyan birden çok bey bulunduğu için kimliği ayrıntılı biçimde tartışılır (doğrulanacak).',
    ],
    sources: ['emecen', 'tansel'],
    related: ['baltaoglu', 'deniz-savasi'],
    dogrulanacak: true,
  },
  {
    id: 'turahan-bey',
    title: 'Turahan Bey',
    category: 'kisi',
    subtitle: 'Teselya uç beyi',
    body: [
      'Teselya’daki akıncıların ünlü beyiydi. 1452 sonbaharında oğulları Ahmed ve Ömer Bey’le birlikte Mora’ya akın etti.',
      'Bu sefer, imparatorun Mora’daki kardeşleri Thomas ve Demetrios’un Kostantiniyye’ye yardım göndermesini engelledi. Oyunda hazırlık aşamasındaki Mora seferi kararının komutanıdır.',
    ],
    sources: ['kritovulos', 'emecen', 'sphrantzes'],
    related: ['mora', 'akinci'],
  },
  {
    id: 'orban',
    title: 'Orban (Urban)',
    category: 'kisi',
    subtitle: 'Top dökücü usta',
    body: [
      'Kökeni tartışmalıdır; çoğunlukla Macar ya da Erdelli olarak anılır (doğrulanacak). Doukas’a göre hizmetlerini önce Bizans’a sundu, ama imparator istediği ücreti ödeyemedi; bunun üzerine Sultan’ın yanına geçti.',
      'Edirne’de dökülen dev topun ustası olarak bilinir. Doukas, onun ilk büyük topunun Boğazkesen’e konduğunu ve 1453 kışında Edirne’de dökülen dev topla deneme atışı yapıldığını yazar.',
      'Osmanlı kaynakları ustanın adından çok, dökülen büyük “şâhî” toplardan söz eder. Orban’ın kuşatma sırasında bir topun patlamasıyla öldüğü de anlatılır, ama bu bilgi kesin değildir.',
    ],
    sources: ['doukas', 'kritovulos', 'emecen', 'tansel'],
    related: ['sahi-topu', 'edirne'],
    dogrulanacak: true,
  },
  {
    id: 'aksemseddin',
    title: 'Akşemseddin',
    category: 'kisi',
    subtitle: 'Bayramî şeyhi, Sultan’ın hocası',
    body: [
      'Asıl adı Muhammed Şemseddin’dir; Hacı Bayram-ı Velî’nin halifelerindendir ve tıp, tasavvuf ve dinî ilimlerle uğraşmıştır. Genç Sultan’ın manevi hocalarından sayılır.',
      'Kuşatmada ordugâhta bulundu. 20 Nisan’daki deniz yenilgisinden sonra Sultan’a yazdığı mektup bugüne ulaşmıştır: şeyh, askerin moralinin bozulduğunu, kararlılık gösterilmesini, gevşeklerin cezalandırılıp yiğitlerin ödüllendirilmesini öğütler.',
      'Fetihten sonra Eyüp Sultan’ın (Ebû Eyyûb el-Ensârî) kabrinin yerini onun bulduğu rivayet edilir. Oyunda moral olaylarında rol alır.',
    ],
    sources: ['aksemseddin', 'inalcik', 'emecen'],
    related: ['kaynak-aksemseddin', 'fatih'],
  },
  {
    id: 'ulubatli-hasan',
    title: 'Ulubatlı Hasan',
    category: 'kisi',
    subtitle: 'Yeniçeri',
    body: [
      'Bursa yakınlarındaki Ulubat’tan (Lopadion) iri yapılı bir yeniçeriydi. Kritovoulos, son hücumda otuz kadar yoldaşıyla surun üstüne ilk çıkanlardan olduğunu, ok ve taş yağmuru altında savaşıp düştüğünü anlatır.',
      'Türk geleneğinde sancağı burca diken kahraman olarak anılır. Bu ayrıntı yaygın anlatıdır; Kritovoulos’un metni onun surlara ilk çıkanlardan olduğunu ve orada şehit düştüğünü vurgular.',
    ],
    sources: ['kritovulos', 'emecen'],
    related: ['son-hucum', 'yeniceri-ocagi'],
  },
  {
    id: 'musliheddin',
    title: 'Müslihiddin Ağa',
    category: 'kisi',
    subtitle: 'Rumeli Hisarı’nın mimarı (geleneğe göre)',
    body: [
      'Geleneksel olarak Rumeli Hisarı’nın mimarı kabul edilir. Hisarın planını ve yapım işlerini yönettiği anlatılır.',
      'Hayatı hakkında kaynaklarda pek az bilgi vardır; adının ve rolünün ayrıntıları araştırmacılar arasında tartışmalıdır (doğrulanacak).',
    ],
    sources: ['emecen'],
    related: ['rumeli-hisari'],
    dogrulanacak: true,
  },
  {
    id: 'hunyadi',
    title: 'Hunyadi Yanoş',
    category: 'kisi',
    subtitle: 'Macar naibi ve komutanı',
    body: [
      'Macaristan’ın en güçlü komutanıydı; 1444 Varna ve 1448 Kosova savaşlarında Osmanlılara karşı Haçlı ordularını yönetti. 1446–1453 arasında genç kral adına naiplik yaptı.',
      'Kasım 1451’de Sultan’la üç yıllık bir ateşkes imzaladı (doğrulanacak). Doukas, kuşatma sırasında ordugâha bir Macar elçiliğinin geldiğini yazar. 1456’da Belgrad’ı Osmanlılara karşı savundu ve kısa süre sonra vebadan öldü.',
    ],
    sources: ['inalcik', 'emecen', 'doukas'],
    related: ['venedik'],
  },

  // ───────────── Bizans ve Latinler ─────────────
  {
    id: 'konstantinos',
    title: 'XI. Konstantinos Palaiologos',
    category: 'kisi',
    subtitle: 'Son Bizans imparatoru (1449–1453)',
    body: [
      '1405’te doğdu. İmparator olmadan önce Mora despotuydu. 1449’da Mistra’da imparator ilan edildi ve Kostantiniyye’ye geldi.',
      'Batı’dan yardım alabilmek için 1452 Aralık’ında kilise birliğinin Ayasofya’da ilan edilmesine razı oldu. Kuşatmada Giustiniani ile birlikte Topkapı ve Lykos vadisini savundu ve son teslim çağrısını reddetti.',
      '29 Mayıs’ta son çarpışmada öldü; cesedinin kesin olarak bulunup bulunmadığı kaynaklarda farklı anlatılır.',
    ],
    sources: ['sphrantzes', 'kritovulos', 'emecen', 'doukas'],
    related: ['giustiniani', 'teslim-teklifi', 'kilise-birligi'],
  },
  {
    id: 'giustiniani',
    title: 'Giovanni Giustiniani Longo',
    category: 'kisi',
    subtitle: 'Cenevizli komutan',
    body: [
      'Ocak 1453’te kendi parasıyla tuttuğu yedi yüz kadar askerle Kostantiniyye’ye geldi. İmparator onu kara surlarının savunmasının başına getirdi.',
      'Savunmayı en zayıf kesim olan Topkapı–Lykos vadisinde topladı; gedikleri geceleri kazık, fıçı ve toprakla kapatan onarım düzeni onun eseridir.',
      '29 Mayıs sabahı ağır yaralandı ve savaş alanından götürüldü; bu, savunmanın çözülmesini hızlandırdı. Sakız’da kısa süre sonra öldü. Venedikli Barbaro ve Leonardo onu suçlar; bu yargılar Ceneviz–Venedik rekabetinden etkilenmiş olabilir.',
    ],
    sources: ['kritovulos', 'barbaro', 'leonardo', 'sphrantzes', 'emecen'],
    related: ['konstantinos', 'lykos', 'topkapi'],
  },
  {
    id: 'notaras',
    title: 'Loukas Notaras',
    category: 'kisi',
    subtitle: 'Megas doux (Bizans başamirali)',
    body: [
      'Bizans’ın en zengin ve en etkili devlet adamlarından biriydi. Kuşatmada Haliç surlarının bir bölümünü savundu.',
      'Kilise birliğine karşı olanlar arasında anılır. Fetihten birkaç gün sonra idam edildi (ayrıntılar kaynaklarda farklıdır, doğrulanacak).',
    ],
    sources: ['doukas', 'sphrantzes', 'emecen'],
    related: ['halic', 'kilise-birligi'],
  },
  {
    id: 'johannes-grant',
    title: 'Johannes Grant',
    category: 'kisi',
    subtitle: 'Karşı lağım ustası',
    body: [
      'Sphrantzes’e göre Osmanlı lağımlarına karşı tünelleri yöneten mühendisti. “Alaman” (Alman) diye anılır; bazı araştırmacılar onun İskoç olabileceğini düşünür (doğrulanacak).',
      'Mayıs ortasından itibaren Osmanlı tünellerini bulup karşı tünellerle yok etti; tünelleri dumanla ve ateşle doldurdu, desteklerini yaktı. Oyunda Bizans’ın karşı lağım becerisini temsil eder.',
    ],
    sources: ['sphrantzes', 'barbaro', 'emecen'],
    related: ['lagim', 'blahernai'],
    dogrulanacak: true,
  },
  {
    id: 'minotto',
    title: 'Girolamo Minotto',
    category: 'kisi',
    subtitle: 'Venedik balyosu',
    body: [
      'Kostantiniyye’deki Venediklilerin temsilcisiydi. Kuşatmada Venedikliler Blahernai sarayı çevresini savundu.',
      'Şehir düştükten sonra esir alınıp idam edildi (doğrulanacak).',
    ],
    sources: ['barbaro', 'emecen'],
    related: ['blahernai', 'venedik'],
  },
  {
    id: 'orhan-celebi',
    title: 'Şehzade Orhan',
    category: 'kisi',
    subtitle: 'Bizans’ta yaşayan Osmanlı şehzadesi',
    body: [
      'Süleyman Çelebi’nin torunudur ve Osmanlı tahtında hak iddia edebilecek bir şehzade olarak Bizans’ta yaşıyordu. Bizans, bu şehzadeyi Osmanlılara karşı bir koz olarak kullanmaya çalıştı.',
      'Doukas’a göre 1451’de imparatorun elçileri, Orhan’ın geçimi için ödenen paranın artırılmasını istedi; bu istek Osmanlı sarayında tepkiyle karşılandı. Kuşatmada Marmara surlarının bir kesimini adamlarıyla savunduğu ve şehir düşerken öldüğü anlatılır (doğrulanacak).',
    ],
    sources: ['doukas', 'inalcik', 'emecen'],
    related: ['marmara-surlari'],
    dogrulanacak: true,
  },
  {
    id: 'isidoros',
    title: 'Kardinal İsidoros',
    category: 'kisi',
    subtitle: 'Papa’nın elçisi',
    body: [
      'Kiev metropolitiydi ve 1439 Floransa Konsili’nde kilise birliğini destekledi. 1452 sonbaharında yanında iki yüz kadar okçuyla Kostantiniyye’ye geldi.',
      '12 Aralık 1452’de Ayasofya’da birlik ayinini yönetti. Kuşatmada savunmaya katıldı, şehir düşünce kılık değiştirerek kaçmayı başardı.',
    ],
    sources: ['doukas', 'leonardo', 'emecen'],
    related: ['kilise-birligi', 'gennadios'],
  },
  {
    id: 'gennadios',
    title: 'Gennadios Scholarios',
    category: 'kisi',
    subtitle: 'Keşiş, kilise birliğinin karşıtı',
    body: [
      'Bizans’ın önde gelen âlimlerinden biriydi. Bir zamanlar kilise birliğini desteklemişken sonradan birliğin en sert karşıtı oldu ve kuşatmadan önce birliğe karşı çıkanların sözcüsü haline geldi.',
      'Fetihten sonra Sultan onu Rum Ortodoks patriği olarak atadı (1454). Böylece Osmanlı yönetiminde patrikliğin yeniden kurulmasında kilit rol oynadı.',
    ],
    sources: ['emecen', 'inalcik', 'doukas'],
    related: ['kilise-birligi', 'isidoros', 'fatih'],
  },
  {
    id: 'antonio-rizzo',
    title: 'Antonio Rizzo',
    category: 'kisi',
    subtitle: 'Venedikli kaptan',
    body: [
      'Kasım 1452’de Karadeniz’den buğday getiren gemisiyle Boğazkesen’in önünden durmadan geçmeye çalıştı. Hisarın topları gemiyi batırdı.',
      'Doukas ve Barbaro’ya göre Rizzo ve tayfası yakalanıp Dimetoka’daki Sultan’ın huzuruna götürüldü ve idam edildi (ayrıntılar doğrulanacak). Olay Boğaz’ın kapandığını ilan eden bir işaret oldu ve Venedik’te büyük tepki uyandırdı.',
    ],
    sources: ['doukas', 'barbaro', 'emecen'],
    related: ['rumeli-hisari', 'venedik'],
  },
];
